config/routes.rb
Rails.application.routes.draw do
  
  resources :people

end

app/models/person.rb
class Person

  attr_accessor :id, :first_name, :middle_name, :last_name, :suffix, :email, :phone

  def initialize(attributes_hash)
    @id = attributes_hash["id"]
    @first_name = attributes_hash["first_name"]
    @middle_name = attributes_hash["middle_name"]
    @last_name = attributes_hash["last_name"]
    @suffix = attributes_hash["suffix"]
    @email = attributes_hash["email"]
    @phone = attributes_hash["phone"]
  end

  def full_name
    return "#{self.first_name} #{self.middle_name} #{self.last_name} #{self.suffix}"
  end

  def self.find(id)
    hash = Unirest.get("#{ENV['API_DOMAIN']}/api/v1/people/#{id}.json", 
              headers:{ "Accept" => "application/json", "Authorization" => "Token token=#{ENV['PEOPLE_API_KEY']}", "X-User-Email" => "#{ENV['PEOPLE_API_EMAIL']}" }).body
    return Person.new(hash)
  end

  def self.all
    array = Unirest.get("#{ENV['API_DOMAIN']}/api/v1/people.json", headers:{ "Accept" => "application/json", "Authorization" => "Token token=#{ENV['PEOPLE_API_KEY']}", "X-User-Email" => "#{ENV['PEOPLE_API_EMAIL']}" }).body
    return array.map{ |hash| Person.new(hash) }
  end

  # REMINDER ABOUT WHAT attr_accessor IS A SHORTCUT FOR:

  # def first_name
  #   return @first_name
  # end

  # def first_name=(name)
  #   @first_name = name
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new

  end

  def create
    @person = Unirest.post("#{ENV['API_DOMAIN']}/api/v1/people.json",
              headers:{ "Accept" => "application/json", "Authorization" => "Token token=#{ENV['PEOPLE_API_KEY']}", "X-User-Email" => "#{ENV['PEOPLE_API_EMAIL']}" },
              parameters: { :person => 
                            {
                              :first_name => params[:first_name],
                              :middle_name => params[:middle_name],
                              :last_name => params[:last_name],
                              :suffix => params[:suffix],
                              :email => params[:email],
                              :phone => params[:phone]
                            }
                          }
              ).body

    redirect_to person_path(@person["id"])
  end

  def edit
    @person = Unirest.get("#{ENV['API_DOMAIN']}/api/v1/people/#{params[:id]}.json", 
                  headers:{ "Accept" => "application/json", "Authorization" => "Token token=#{ENV['PEOPLE_API_KEY']}", "X-User-Email" => "#{ENV['PEOPLE_API_EMAIL']}" }).body
  end

  def update
    @person = Unirest.patch("#{ENV['API_DOMAIN']}/api/v1/people/#{params[:id]}.json",
              headers:{ "Accept" => "application/json", "Authorization" => "Token token=#{ENV['PEOPLE_API_KEY']}", "X-User-Email" => "#{ENV['PEOPLE_API_EMAIL']}" },
              parameters: { :person => 
                            {
                              :first_name => params[:first_name],
                              :middle_name => params[:middle_name],
                              :last_name => params[:last_name],
                              :suffix => params[:suffix],
                              :email => params[:email],
                              :phone => params[:phone]
                            }
                          }
              ).body

    redirect_to person_path(@person["id"])
  end

  def destroy
    Unirest.delete("#{ENV['API_DOMAIN']}/people/api/v1/#{params[:id]}.json",
      headers:{ "Accept" => "application/json", "Authorization" => "Token token=#{ENV['PEOPLE_API_KEY']}", "X-User-Email" => "#{ENV['PEOPLE_API_EMAIL']}" })

    redirect_to people_path
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PeopleWebclient</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/edit.html.erb
<h1>Edit a person</h1>

<div class="form">
  <%= form_tag(person_path(@person["id"]), :method => :patch) do %>
    <fieldset>
      <%= label_tag :first_name %>
      <%= text_field_tag :first_name, @person["first_name"] %><br/>

      <%= label_tag :middle_name %>
      <%= text_field_tag :middle_name, @person["middle_name"] %><br/>

      <%= label_tag :last_name %>
      <%= text_field_tag :last_name, @person["last_name"] %><br/>

      <%= label_tag :suffix %>
      <%= text_field_tag :suffix, @person["suffix"] %><br/>

      <%= label_tag :email %>
      <%= text_field_tag :email, @person["email"] %><br/>

      <%= label_tag :phone %>
      <%= text_field_tag :phone, @person["phone"] %><br/>

      <%= submit_tag "Update Person" %>
    </fieldset>
  <% end %>
</div>

app/views/people/index.html.erb
<h1>Lots of people!</h1>
<% @people.each do |person| %>
  <h3><%= person.full_name %></h3>
  <h4><%= person.email %></h4>
  <h4><%= person.phone %></h4>
<% end %>

app/views/people/new.html.erb
<h1>Create a new person</h1>

<div class="form">
  <%= form_tag(people_path) do %>
    <fieldset>
      <%= label_tag :first_name %>
      <%= text_field_tag :first_name %><br/>

      <%= label_tag :middle_name %>
      <%= text_field_tag :middle_name %><br/>

      <%= label_tag :last_name %>
      <%= text_field_tag :last_name %><br/>

      <%= label_tag :suffix %>
      <%= text_field_tag :suffix %><br/>

      <%= label_tag :email %>
      <%= text_field_tag :email %><br/>

      <%= label_tag :phone %>
      <%= text_field_tag :phone %><br/>

      <%= submit_tag "Create Person" %>
    </fieldset>
  <% end %>
</div>

app/views/people/show.html.erb
<h1><%= @person.full_name %></h1>
<h2>Email: <%= @person.email %></h2>
<h3>Phone: <%= @person.phone %></h3>

<%= link_to "Edit", edit_person_path(@person.id) %>
<%= link_to "Delete", person_path(@person.id), :method => :delete %>